# Este es un archivo de ejemplo para configurar los secretos de Streamlit
# Copia este archivo a .streamlit/secrets.toml y actualiza los valores

# Opciu00f3n 1: Estructura anidada (recomendada)
[supabase]
url = "https://.supabase.co"
key = ".."
project_ref = ""
# Si necesitas mu00e1s permisos (para superar las restricciones de RLS), usa el service_role_key
# PRECAUCIU00d3N: Este token tiene permisos completos sobre tu base de datos
# service_role_key = "TU_SERVICE_ROLE_KEY"

# Opcionalmente, puedes agregar credenciales de base de datos para conexiu00f3n directa
# db_user = "postgres."
# db_password = "tu_contraseu00f1a"
# db_host = "aws-0-ca-central-1.pooler.supabase.com"
# db_port = 6543
# db_name = "postgres"
# db_sslmode = "require"

# Opciu00f3n 2: Estructura plana (alternativa)
# url = "https://.supabase.co"
# key = ".."
# project_ref = ""
# service_role_key = "TU_SERVICE_ROLE_KEY"
